# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Classification
                                 A QGIS plugin
 Finding Water and Vegetation via NDVI
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-22
        copyright            : (C) 2021 by gkcm
        email                : kristina.maahn@studs.hs-bochum.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Classification class from file Classification.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .classification import Classification
    return Classification(iface)
